// <auto-generated />
namespace IdentityMvc.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GoogleAuthFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoogleAuthFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202006261154048_GoogleAuthFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
